'use strict';

// station-6: after a plugin update the generated override would keep the old
// agent body. `start` rewrites any override whose `generated_by` version is
// not the plugin's, once, and says so.

const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { execFileSync } = require('node:child_process');
const tmp = require('./tmp.js');

const TASK = path.join(__dirname, '..', 'scripts', 'task.js');
const VERSION = JSON.parse(fs.readFileSync(path.join(__dirname, '..', 'package.json'), 'utf8')).version;
const SESSION = 'aaaaaaaa-1111-2222-3333-444444444444';

function fixture(stamp) {
    const d = tmp('fankeel-agentfile-start-');
    fs.mkdirSync(path.join(d, '.fankeel'), { recursive: true });
    fs.writeFileSync(path.join(d, '.fankeel', 'profile.json'), JSON.stringify({ 'agent.fankeel-reader.model': 'haiku' }));
    const file = path.join(d, '.claude', 'agents', 'fankeel-reader.md');
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, '---\nname: fankeel-reader\nmodel: haiku\ngenerated_by: fankeel ' + stamp + '\n---\nold body\n');
    return { d, file };
}

function start(d) {
    const cfg = path.join(d, 'cfg');
    return execFileSync(process.execPath, [TASK, 'start', '--task', 'probe', '--session', SESSION, '--root', d, '--claude-dir', cfg],
        { encoding: 'utf8', cwd: d, env: Object.assign({}, process.env, { CLAUDE_CONFIG_DIR: cfg }) });
}

test('start rewrites an override generated by another plugin version', () => {
    const { d, file } = fixture('0.0.1');
    const out = start(d);
    const text = fs.readFileSync(file, 'utf8');
    assert.match(text, new RegExp('^generated_by: fankeel ' + VERSION.replace(/\./g, '\.') + '$', 'm'));
    assert.match(text, /^model: haiku$/m);
    assert.match(text, /You are a reader\./, 'the body is the plugin\'s current one');
    assert.match(out, /agent file: rewritten for /);
});

test('start leaves an override at the plugin\'s own version untouched and says nothing about it', () => {
    const { d, file } = fixture(VERSION);
    const before = fs.readFileSync(file, 'utf8');
    const out = start(d);
    assert.equal(fs.readFileSync(file, 'utf8'), before);
    assert.doesNotMatch(out, /agent file:/);
});

test('the usage names profile unset', () => {
    let out = '';
    try {
        execFileSync(process.execPath, [TASK, 'nope'], { encoding: 'utf8', cwd: tmp('fankeel-agentfile-usage-') });
    } catch (e) {
        out = String(e.stdout || '') + String(e.stderr || '');
    }
    assert.match(out, /profile show\|set <key> <value>\|unset <key>\|suggest/);
});
