'use strict';

// TODO entries as files (docs/99-archive/2026-09-29-todo-files-design.md):
// the entry-file format, todo.js as the one writer, and load() giving the
// folder the same shapes a hand-written TODO.md gives.
const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { execFileSync } = require('node:child_process');

const lib = require('../lib/todo.js');
const { main } = require('../scripts/todo.js');
const tmp = require('./tmp.js');

const SCRIPT = path.join(__dirname, '..', 'scripts', 'todo.js');
const NOW = new Date(2026, 8, 25, 12, 0).getTime();

const TODO = [
  '# TODO', '', 'A hand-written index.', '',
  '## Ready', '', '- 〔alpha〕Do the thing — [a.md](docs/a.md).', '',
  '## Needs a decision', '', '- 〔beta〕Decide that — [a.md](docs/a.md).', '',
  '## Blocked', '', '### Waits for release', 'upstream: lib 2.0. 09-20.', '',
  '- 〔gamma〕After release — [a.md](docs/a.md).', '- 〔gamma〕Second one — [a.md](docs/a.md).', '',
  '## Watch', '', '### If it recurs', 'if: it happens again. 09-21.', '',
  '- no label here — [a.md](docs/a.md).', '',
].join('\n');

const COMPLETIONS = [
  '# TODO completions', '', '```',
  '- original: 〔delta〕Closed last week — [a.md](docs/a.md).', '  disposition: done',
  '  sha: 0123456789abcdef0123456789abcdef01234567', '',
  '- original: <the entry\'s text, verbatim>', '  disposition: done | measured-no-change | abandoned',
  '  sha: <the commit that closed it>', '```', '',
].join('\n');

function project(withBucket) {
  const dir = tmp('fankeel-todofiles-');
  const put = (rel, text) => {
    fs.mkdirSync(path.dirname(path.join(dir, rel)), { recursive: true });
    fs.writeFileSync(path.join(dir, rel), text);
  };
  put('TODO.md', TODO);
  put('docs/a.md', '# a\n');
  put(lib.COMPLETIONS_PAGE, COMPLETIONS);
  const buckets = [{ path: 'docs', role: 'reference', depth: 1 }];
  if (withBucket) buckets.push({ path: 'docs/todo', role: 'todo' });
  put('.fankeel/docs.json', JSON.stringify({ buckets }));
  return dir;
}

const shape = (loaded) => ({
  entries: loaded.entries.map((e) => ({ section: e.section, text: e.text })),
  timings: loaded.timings.map((t) => ({ section: t.section, title: t.title, kind: t.kind, event: t.event,
    stamp: t.stamp, items: t.items.length })),
});

test('an entry file round-trips through serialize and parse', () => {
  const e = { label: 'x', title: 'A title', description: 'a line with `code` — [a.md](docs/a.md).', state: 'blocked',
    link: 'docs/a.md', group: 'Waits', timing: 'after: y', stamp: '2026-09-20',
    done: { at: '2026-09-29', sha: 'abcdef1', disposition: 'done', session: 's-1' }, body: 'Background.\n\nTried z.' };
  assert.deepEqual(lib.parse(lib.serialize(e)), e);
  const bare = { label: '', title: 't', description: 'd', state: 'ready', link: '', group: '', timing: '', stamp: '',
    done: null, body: '' };
  assert.deepEqual(lib.parse(lib.serialize(bare)), bare);
  assert.ok(lib.ID.test('stage-agents-12') && !lib.ID.test('Stage_1'));
  assert.ok(lib.ISO.test('2026-09-29') && lib.STATES.includes('done'));
  assert.equal(lib.isoDay(NOW), '2026-09-25');
});

test('migrate turns TODO.md and the completions page into entry files, and load() reads both in one shape', () => {
  const file = project(false);
  const folder = project(true);
  const before = lib.load(file, NOW);
  assert.equal(before.mode, 'file');
  assert.equal(lib.folderOf(file), null);
  const r = lib.migrate(folder, NOW);
  assert.deepEqual([r.open, r.done, r.left.length], [5, 1, 0]);
  const after = lib.load(folder, NOW);
  assert.equal(after.mode, 'folder');
  assert.equal(lib.folderOf(folder), 'docs/todo');
  assert.deepEqual(shape(after), shape(before));
  assert.deepEqual(after.entries.map((e) => e.id), ['alpha-1', 'beta-1', 'gamma-1', 'gamma-2', 'entry-1']);
  assert.deepEqual(after.done.map((d) => [d.id, d.sha, d.disposition]),
    [['delta-1', '0123456789abcdef0123456789abcdef01234567', 'done']]);
  const gamma = lib.readFolder(folder, 'docs/todo').find((e) => e.id === 'gamma-2');
  assert.deepEqual([gamma.group, gamma.timing, gamma.stamp], ['Waits for release', 'upstream: lib 2.0', '2026-09-20']);
  assert.equal(lib.render(folder, lib.readFolder(folder, 'docs/todo'), 'docs/todo').text, after.text);
  assert.throws(() => lib.migrate(folder, NOW), /runs once/);
});

test('todo.js index rewrites TODO.md byte for byte, and new and done move an entry through it', () => {
  const dir = project(true);
  lib.migrate(dir, NOW);
  const index = fs.readFileSync(path.join(dir, 'TODO.md'), 'utf8');
  execFileSync(process.execPath, [SCRIPT, 'index', '--root', dir], { encoding: 'utf8', cwd: dir });
  assert.equal(fs.readFileSync(path.join(dir, 'TODO.md'), 'utf8'), index);
  assert.equal(lib.writeIndex(dir), index);
  assert.match(index, /^Generated by fankeel's `scripts\/todo\.js index` from `docs\/todo\/`/m);

  const made = main(['new', '--root', dir, '--label', 'eps', '--title', 'New one', '--description', 'a new entry',
    '--state', 'ready'], NOW);
  assert.equal(made.ok, true, made.text);
  assert.match(fs.readFileSync(path.join(dir, 'TODO.md'), 'utf8'), /^- 〔eps〕a new entry$/m);

  const shut = main(['done', 'eps-1', '--root', dir, '--sha', 'abcdef1', '--session', 'sess-1'], NOW);
  assert.equal(shut.ok, true, shut.text);
  assert.doesNotMatch(fs.readFileSync(path.join(dir, 'TODO.md'), 'utf8'), /a new entry/);
  const done = lib.load(dir, NOW).done.find((d) => d.id === 'eps-1');
  assert.deepEqual([done.sha, done.session, done.disposition, done.at], ['abcdef1', 'sess-1', 'done', '2026-09-25']);
  assert.equal(main(['done', 'eps-1', '--root', dir, '--sha', 'abcdef1'], NOW).ok, false, 'closed once, not twice');
  assert.equal(main(['done', 'alpha-1', '--root', dir], NOW).ok, false, 'no sha, no close');
});

test('fromLine and add make an entry out of one TODO.md-style line', () => {
  const dir = project(true);
  fs.mkdirSync(path.join(dir, 'docs', 'todo'));
  const f = lib.fromLine('  〔station〕a  question：with detail ', 'docs/a.md', 'decision');
  assert.deepEqual(f, { label: 'station', title: 'a question', description: 'a question：with detail',
    state: 'decision', link: 'docs/a.md' });
  const made = lib.add(dir, f);
  assert.deepEqual([made.id, made.file], ['station-1', 'docs/todo/station-1.md']);
  assert.match(fs.readFileSync(path.join(dir, 'TODO.md'), 'utf8'),
    /^- 〔station〕a question：with detail — \[a\.md\]\(docs\/a\.md\)\.$/m);
  const shut = lib.close(dir, 'station-1', { sha: 'abcdef1', at: '2026-09-29' });
  assert.equal(shut.file, 'docs/todo/station-1.md');
  assert.throws(() => lib.add(dir, Object.assign({}, f, { id: 'station-1' })), /never reused/);
});

test('ids collate numerically: x-2 before x-10 in readFolder, x-10 before x-2 in done', () => {
  const dir = project(true);
  fs.mkdirSync(path.join(dir, 'docs', 'todo'));
  for (const id of ['x-10', 'x-2']) {
    const e = { label: 'x', title: id, description: id, state: 'done', link: '', group: '', timing: '', stamp: '',
      done: { at: '2026-09-29', sha: 'abcdef1', disposition: 'done', session: '' }, body: '' };
    fs.writeFileSync(path.join(dir, 'docs', 'todo', id + '.md'), lib.serialize(e));
  }
  assert.deepEqual(lib.readFolder(dir, 'docs/todo').map((e) => e.id), ['x-2', 'x-10']);
  assert.deepEqual(lib.load(dir, NOW).done.map((d) => d.id), ['x-10', 'x-2']);
});

test('this repository keeps entry files, and its TODO.md is what todo.js index writes', () => {
  const root = path.join(__dirname, '..');
  const loaded = lib.load(root);
  assert.equal(loaded.mode, 'folder');
  assert.equal(loaded.folder, 'docs/90-agent/todo');
  assert.equal(fs.readFileSync(path.join(root, 'TODO.md'), 'utf8').replace(/\r\n/g, '\n'), loaded.text);
  assert.match(loaded.text, /\[todo\.md\]\(docs\/90-agent\/reference\/todo\.md\)/);
});

test('readFolder: a missing folder is empty, but a path that is not a folder throws', () => {
  const dir = tmp('fankeel-readfolder-');
  assert.deepEqual(lib.readFolder(dir, 'docs/todo'), []);
  fs.mkdirSync(path.join(dir, 'docs'), { recursive: true });
  fs.writeFileSync(path.join(dir, 'docs', 'todo'), 'a file where the folder should be\n');
  assert.throws(() => lib.readFolder(dir, 'docs/todo'), (e) => e.code !== 'ENOENT');
});

test('writeIndex does not rewrite TODO.md from a folder it could not read', () => {
  const dir = project(true);
  fs.mkdirSync(path.join(dir, 'docs', 'todo'), { recursive: true });
  fs.writeFileSync(path.join(dir, 'TODO.md'), 'kept\n');
  const real = fs.readdirSync;
  const denied = Object.assign(new Error('EACCES: permission denied'), { code: 'EACCES' });
  fs.readdirSync = (p, ...rest) => {
    if (path.resolve(String(p)) === path.join(dir, 'docs', 'todo')) throw denied;
    return real.call(fs, p, ...rest);
  };
  try {
    assert.throws(() => lib.writeIndex(dir), (e) => e === denied);
  } finally {
    fs.readdirSync = real;
  }
  assert.equal(fs.readFileSync(path.join(dir, 'TODO.md'), 'utf8'), 'kept\n');
});

test('load: a TODO.md that cannot be read throws, and only a missing one is "no TODO"', () => {
  const dir = tmp('fankeel-loadfile-');
  assert.equal(lib.load(dir), null);
  fs.mkdirSync(path.join(dir, 'TODO.md'));
  assert.throws(() => lib.load(dir), (e) => e.code === 'EISDIR');
});
